aws:
  accessKey: ${AWS_ACCESS_KEY:2}
  secretKey: ${AWS_SECRET_ACCESS_KEY:1}
  region: ${AWS_REGION:us-east-1}
  #folder: ${AWS_FOLDER:'C:\Users\vsvdev\Desktop\s3server\s3'}
  folder: ${AWS_FOLDER:~/s3}

server:
  port: ${AWS_PORT:7777}

spring:
  banner:
    image:
      location: classpath:resources/banner.txt




